USE [getbuild_mate]
GO

/****** Object:  Table [dbo].[UserBusinessType]    Script Date: 01/08/2014 23:04:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UserBusinessType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[businessType] [varchar](20) NOT NULL,
 CONSTRAINT [PK_UserBusinessType] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

